### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by stephenneale** [stephenneale/seng371-group16#1]
To do:

- [ ] Get assigned a brightspace group
- [ ] Select a project topic to work on
- [ ] Become a client or developer group (?)

More to add later when we can see the assignment.

**Comment by stephenneale** [comment]
Main key features wanted on University Systems:

1. Login and verification system
3. System to register/drop for courses
4. System to view grades of current and past courses
5. System to view online content delivered by courses such as lectures, overviews, notes, assignment files, etc
6. Calendar system for current courses with meeting locations
7. A separate course deadlines and assignments calendar
8. Mobile device optimized 
9. Discussion system in each course - directly to prof?
10. Have an announcement module for prof and administrative announcements

**Comment by stephenneale** [comment]
Discord link: https://discord.gg/6QrBeZPa

**Comment by matt-lebl** [comment]
I've [created a milestone](https://github.com/stephenneale/seng371-group16/milestone/1) for Assignment 1 and split up its requirements into various issues. So, I'll close this issue since it isn't needed anymore.
