### ISSUE TITLE
Implement a limited functionality app

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#28]
> The goal here is just not to code a fully functional app (you don't have enough time for this) - but to make serious progress with coding a running application. Make sure this application goes through CI/CD tools.

**Comment by matt-lebl** [comment]
I'm thinking we can have some very bare-bones functionality as follows:

- A single page that represents a user's homepage (no login functionality, webapp loads as if a user was already logged in),
- A list of courses is visible,
- Clicking on a course shows a listing of content that is available to be viewed,
- Course content is not interactive, functionality ends with the list.

What do you think?

**Comment by matt-lebl** [comment]
Backend side of this is complete. I defined three endpoints:

- `/courses` — lists all courses (there is just one in the sample, but adding more is relatively easy
- `/courses/{id}` — provides more detailed info about a course 
- `/content/{courseId}` — provides the content for the course with the given ID

**Comment by stephenneale** [comment]
A first-draft functional DimSpace has been developed and can be found in the following [PR](https://github.com/stephenneale/seng371-group16/pull/34). Functionalities include a Home page, a Course Home page, and communication with the Spring API.
