### ISSUE TITLE
CI/CD Pipeline for Frontend

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#31]

**Comment by stephenneale** [comment]
CI workflow for the Django based frontend is now up and running on main via the following commits:

- [Add DimSpace CI and basic tests](https://github.com/stephenneale/seng371-group16/commit/e48390ba4f7dd0309b677d2a0fe5465280d00330)
- [Update Run Tests directory](https://github.com/stephenneale/seng371-group16/commit/89b0d12363faed24d70dd6eb5ed4531a527e83a7)
- [Add dimspace CI badge to README](https://github.com/stephenneale/seng371-group16/commit/3d690b33fc5d89746af974f9d54f803aa744860b)

**Comment by stephenneale** [comment]
As for CD, the django webapp should be launched alongside the spring backend within a docker container on a kubernetes cluster or a linux VM.
