### ISSUE TITLE
Create summary document for Assignment 2

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#37]
Summarise changes that we made to requirements doc, architecture diagram, etc., also link to new documents like Request for Changes. Summarise new functionality coded in app, and also explain configured CI/CD.

- [x] Request for Changes in Requirement Document
- [x] Update the Requirement Document
- [x] Update the Architecture (Mental Model) — including description of architecture diagram.
- [x] Creating a development pipeline that supports Continuous Integration and Continuous Delivery (CI/CD)
- [x] Implement a limited functionality app

**Comment by matt-lebl** [comment]
@stephenneale may you please summarise for me the frontend CI stuff that you implemented? How it works, if it runs tests, etc. :smiley:

**Comment by stephenneale** [comment]
## Frontend CI Implementation Summary

The Django based frontend of the DimSpace project is now tested whenever changes are pushed to the repo. The tests are initiated by a new workflow file `dimspace-ci.yml`, which utilizes Python 3.9 and Django's built in testing feature to check whether any recent changes end up breaking the frontend. This built in feature runs the `tests.py` file within the `dimapp/` folder, in which some basic response checking tests have been added.

How it works:

1. Upon a push or pull-request to the repository, the CI workflow file `dimspace-ci.yml` is automatically run. This file first sets up a Python 3.9 environment to run the procedure in.
2. The file then invokes Django's built in testing functionality off the main `manage.py` file via `python3 manage.py test`
3. The Django testing functionality then checks `tests.py`, and runs any classes that have `test` at the start of their name, while running the `setUp` class beforehand.
4. If all test cases pass, no error is returned and the workflow cleans up the testing environment.
