### ISSUE TITLE
Make each piece of course content clickable

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#45]
When a piece of course content is clicked, it should open its own page. This should basically just be a frontend change, but an API endpoint should be hit each time the user opens a page, to power the "recent pages" functionality.

**Comment by matt-lebl** [comment]
You can use the `view` endpoint defined in ad03036.

**Comment by stephenneale** [comment]
Courses now have content categorized into 4 types:
- Announcements
- Lectures
- Assignments
- Labs

As for the scope of the project we only have "Announcement" data, functionality has been added to allow the viewing of content in the Announcement section. Upon viewing an announcement, the backed recent post endpoint will be reached, and the new Frequently Viewed bar on the homepage will be updated accordingly. See more in the developments [PR](https://github.com/stephenneale/seng371-group16/pull/49).
