### ISSUE TITLE
Brainstorm software self-adaptation

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#5]
Our system should have some self-adaptation component. We need to brainstorm what this could look like in our project.

**Comment by andrewpetten** [comment]
Stephens idea I believe: System keeps track of classes clicked, displays classes from most clicked - least clicked?

**Comment by matt-lebl** [comment]
> Stephens idea I believe: System keeps track of classes clicked, displays classes from most clicked - least clicked?

Yup! This particular point was sent to our client team for their RFP. [See here](https://github.com/stephenneale/seng371-group16/blob/main/as-developers/features.md?plain=1#L26)

**Comment by matt-lebl** [comment]
I think our frecency idea is great but too simple to get a good grade. I have some ideas about how to integrate self-adaptation into our system so I'll take care of this one.
