### ISSUE TITLE
Software Self Adaptation

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#53]
> Write in detail about the creative ways you adapted the software self-adaptation in your applications.

**Comment by matt-lebl** [comment]
i'm honestly kinda stumped for what to do here. currently our software self adaptation piece is that list datastructure that powers the "recently viewed" part of the homepage. anything else we should write?

@stephenneale @SamurayG @andrewpetten

**Comment by stephenneale** [comment]
The "Recently Viewed" feature on the DimSpace home page is a tool that allows users to quickly access previously viewed course content. The implementation of this feature involves software evolution, which is the process of making continuous improvements to software through updates and iterations. As users view course content on DimSpace, the Django framework records their browsing history and stores it in the Springboot API. The two then work together to sort the data and display the most recently viewed items to the user. As the platform evolves, we can enhance this feature by incorporating user feedback, improving the algorithms to a "frecent" approach, and optimizing the database for faster retrieval. Through this continuous process of evolution, the "Recently Viewed" feature can become more intuitive, personalized, and efficient over time, leading to a better user experience.
