### ISSUE TITLE
Implement grade weights + cumulative grade

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#57]
## Frontend

A new `weight` field will be added to API responses alongside grades where appropriate. This will be a value between 0 and 1, representing the contribution of that item's grade to the total grade of the course. Using this value in combination with the grades of each item, calculate the total cumulative grade achieved to date. Where a grade item is listed but no grade is assigned, assume the grade is 0%.

## Backend

Add `weight` field to each grade item, and return this weight field in API responses where the grade is returned.

**Comment by matt-lebl** [comment]
just added a new thing

```json
{
    "comment": null,
    "itemName": "Quiz 2",
    "markDenominator": 5.0,
    "markNumerator": null,
    "percentage": null,
    "weight": 0.01
}
```

**Comment by stephenneale** [comment]
Added my implementation [here](https://github.com/stephenneale/seng371-group16/pull/60), cumulative weights are calculated on loading the "Grades" page and displayed appropriately 😄
