### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#58]
*a.k.a. dim mode*

## Frontend

Add a button that switches the page style to a dark mode, with light text on dark background.

## Backend

Add one POST endpoint to set dark or light mode, and a GET endpoint to check what's currently set.

**Comment by stephenneale** [comment]
After some brainstorming, I think I know how I'm gonna go about this. Could you add a "dark mode" endpoint to the rest API that either returns 0 or 1? This will be toggled by the button to switch between light and dark mode, and depending on what the endpoint returns I can generate the appropriate HTML.

**Comment by matt-lebl** [comment]
@stephenneale Sounds reasonable enough! So if I'm understanding correctly, we'll need one POST endpoint to set dark or light mode, and a GET endpoint to check what's currently set?

**Comment by stephenneale** [comment]
> @stephenneale Sounds reasonable enough! So if I'm understanding correctly, we'll need one POST endpoint to set dark or light mode, and a GET endpoint to check what's currently set?

Yeah that'd work perfect :)

**Comment by matt-lebl** [comment]
On to you, @stephenneale ! 😃

**Comment by matt-lebl** [comment]
Well I should probably explain 😂 

New endpoint: `/darkmode`. Submitting a GET to this endpoint will return a JSON response:

```json
{
    "enabled": false
}
```

In this case indicating that dark mode is off. This operation doesn't toggle, only returns the state of the flag.

To change the flag, submit a POST request to the same endpoint with the same format as the GET response. So a POST that looks like this:

```json
{
    "enabled": true
}
```

…will cause subsequent GETs to return

```json
{
    "enabled": true
}
```

Let me know if you have any questions/notes!

**Comment by matt-lebl** [comment]
(in retrospect PUT would have likely been the more appropriate verb but we out here)

**Comment by stephenneale** [comment]
Everything's working as intended after my implementation found [here](https://github.com/stephenneale/seng371-group16/pull/61), let me know what you think!
