### ISSUE TITLE
Create UI prototypes

### ISSUE THREAD

**Issue by matt-lebl** [stephenneale/seng371-group16#7]
We need to make 4–5 low-fidelity prototypes for the client team.

**Comment by matt-lebl** [comment]
I propose we use [diagrams.net](https://www.diagrams.net), since I think their diagram files can be put under source control with minimal problems. I don't have experience with any other tool, though, so obviously any other ideas are welcome 😃

**Comment by stephenneale** [comment]
Added UI mockups in the following [commit](https://github.com/stephenneale/seng371-group16/pull/23/commits/7a05a66a9008c5fd9359a40246b3a57d4f88dee2), within the [frontend-baseline PR](https://github.com/stephenneale/seng371-group16/pull/23).
